name: Sync Upstream Repository

on:
  schedule:
    # 每天凌晨3点运行（UTC时间）
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          fetch-depth: 0 # 获取完整历史记录

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master # 或你的主分支名称
          git merge upstream/master --allow-unrelated-histories
          # 如果有冲突，这里会失败，你需要手动处理

      - name: Push changes
        run: git push origin master
